### ISSUE TITLE
Not working if market was delisted

### ISSUE THREAD

**Issue by CLIDOapps** [JonathanSchubert/moneymoney-bittrex#1]
Hi, great plugin, but I can't login.
I have several markets with balances which are gone thru delisting.

For example:

Sending: GET https://bittrex.com/api/v1.1/public/getticker?market=BTC-BLITZ
          Received: {"success":false,"message":"INVALID_MARKET","result":null}
          Bittrex.lua:83: attempt to index a nil value

The result of BTC-BLITZ is "null" and crashs the extension.

I tried to fix it in Bittrex.lua but I can`t set a valid SIGNATURE at the bottom. (Is there a how to?)

Greetz

**Comment by JonathanSchubert** [comment]
Thanks for the hint, I had the same issue.
Find the updated extension with a new valid signature in the repo (https://github.com/JonathanSchubert/moneymoney-bittrex/tree/master/dist)

Cheers!
